defaults: &defaults
  adapter: postgresql
  encoding: unicode
  reconnect: true
  min_messages: warning
  pool: 15
  timeout: 5000
  host: localhost

development:
  <<: *defaults
  database: locadora_development
  username: solucao_social
  password: solucao_social

test:
  <<: *defaults
  database: locadora_test
  username: solucao_social
  password: solucao_social

production:
  <<: *defaults
  database: locadora_production
  username: solucao_social
  password: solucao_social
